[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
