# AIFOLIO Elite Pre-Commit DNA Engine
# Phase 1.10∞ - Immortal Commit Protocol
# Essential commit hygiene control

repos:
  # Black - The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        files: \.py$

  # Pre-commit hooks for essential file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        description: "Ensures files end with a newline"
      - id: trailing-whitespace
        description: "Trims trailing whitespace"
      - id: check-added-large-files
        description: "Prevents giant files from being committed"
        args: [--maxkb=1000]
      - id: check-case-conflict
        description: "Checks for files that would conflict in case-insensitive filesystems"
      - id: check-merge-conflict
        description: "Checks for merge conflict strings"

  # isort - Import sorting (new files only)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: \.py$

# Global configuration
default_language_version:
  python: python3

# Fail fast - stop on first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: 3.0.0
