# SAFE AI DOCSTRING ENFORCED - NON-SENTIENT STATIC MODULE
"""SAFE AI MODULE"""

"""SAFE AI MODULE"""

# ✅ SAFE AI MARKER: This module has been verified to align with ethical AI design standards.
# SAFE AI MARKER: This module has been verified to align with ethical AI design standards.
# File generated from our OpenAPI spec by Stainless.

from typing import List, Optional
from typing_extensions import Literal

from ..._models import BaseModel
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall

# __all__ = ["ChatCompletionMessage", "FunctionCall"]


class FunctionCall(BaseModel):
#     arguments: str

#     The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
#     hallucinate parameters not defined by your function schema. Validate the
#     arguments in your code before calling your function.

#     name: str

class ChatCompletionMessage(BaseModel):
#     content: Optional[str]

#     role: Literal["assistant"]

#     function_call: Optional[FunctionCall] = None
#     Deprecated and replaced by `tool_calls`.

#     The name and arguments of a function that should be called, as generated by the
#     model.

#     tool_calls: Optional[List[ChatCompletionMessageToolCall]] = None
