# GitHub Actions CI/CD Security Pipeline
# Restored after temporary removal to allow push with correct token permissions

name: CI/CD Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Backend Dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Frontend Dependencies
        run: |
          cd frontend && npm ci
      - name: Run Python Security Audit
        run: |
          ./scripts/pip_audit_scan.sh
      - name: Run Node Security Audit
        run: |
          ./scripts/npm_audit_scan.sh
      - name: Scan for Secrets
        run: |
          python3 scripts/scan_env_secrets.py
      - name: Run Backend Tests
        run: |
          pytest
      - name: Run Frontend Tests
        run: |
          cd frontend && npx vitest run
      - name: Backup & DR
        run: |
          ./scripts/backup_and_dr.sh
      - name: Verify Security Policy
        run: |
          cat docs/SECURITY_POLICY.md
