name: CI/CD Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies (Python)
        run: pip install -r backend/requirements.txt
      - name: Install dependencies (Node)
        run: |
          cd frontend
          npm ci
      - name: Secrets scanning
        run: python scripts/scan_env_secrets.py
      - name: Dependency audit (npm)
        run: bash scripts/npm_audit_scan.sh
      - name: Dependency audit (pip)
        run: bash scripts/pip_audit_scan.sh
      - name: Backup & DR test
        run: bash scripts/backup_and_dr.sh
      - name: Lint (Python)
        run: |
          pip install flake8
          flake8 backend
      - name: Lint (JS/TS)
        run: |
          cd frontend
          npm run lint || true
      - name: Run frontend tests
        run: |
          cd frontend
          npm test
      - name: Run backend tests
        run: pytest || true
      - name: Verify security policy
        run: cat docs/SECURITY_POLICY.md
