# GitHub Actions Workflow for SAFE AI PMP Backend
name: PMP Backend CI/CD
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          cd backend
          pytest || echo 'No tests yet'
      - name: Build Docker image
        run: |
          cd backend
          docker build -t pmp-backend .
      - name: Deploy to Kubernetes (stub)
        run: echo 'K8s deploy stub - configure for production'
