jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        format: sarif
        output: trivy-results.sarif
        scan-ref: .
        scan-type: fs
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
name: Security Scan
'on':
  schedule:
  - cron: 0 2 * * *
  workflow_dispatch: {}
